# This workflow will run the end-to-end tests
name: Nuevo E2E

on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment to run the tests on'
        required: true
        default: 'production'
        type: choice
        options:
          - 'production'
          - 'testing'
      Browser:
        description: 'Browser to run the tests on'
        required: true
        default: 'chrome'
        type: choice
        options:
          - 'chrome'
          - 'firefox'
          - 'edge'
          - 'electron'
      Test:
        description: 'Test to run'
        required: true
        default: 'sanity test'
        type: choice
        options:
          - 'smoke test'
          - 'sanity test'

jobs:
  run:
    name: Cypress run
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure environment
        env:
          ENVIRONMENT: ${{ github.event.inputs.Environment || 'production' }}
          TEST: ${{ github.event.inputs.Test || 'sanity test' }}
          BROWSER: ${{ github.event.inputs.Browser || 'chrome' }}
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Scheduled run detected, using default values."
            ENVIRONMENT='production'
            TEST='sanity test'
            BROWSER='chrome'
          fi
          echo "Configured Environment: $ENVIRONMENT"
          echo "Test Suite: $TEST"
          echo "Browser: $BROWSER"

          case $ENVIRONMENT in
            production)
              echo "LOCATION=https://www.saucedemo.com/v1" >> "$GITHUB_ENV"
              ;;
            testing)
              echo "LOCATION=https://www.saucedemo.com/v1" >> "$GITHUB_ENV"
              ;;
          esac
          
          case $TEST in
            "sanity test")
              echo "TEST_SUITE=e2e:sanity" >> "$GITHUB_ENV"
              ;;
            "smoke test")
              echo "TEST_SUITE=e2e:smoke" >> "$GITHUB_ENV"
              ;;
          esac

          echo "ENVIRONMENT=$ENVIRONMENT" >> "$GITHUB_ENV"
          echo "BROWSER=$BROWSER" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          npm ci
          npx cypress install

      - name: Run tests
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          LOCATION: ${{ env.LOCATION }}
          TEST_SUITE: ${{ env.TEST_SUITE }}
          BROWSER: ${{ env.BROWSER }}
        run: npm run $TEST_SUITE -- --browser $BROWSER

      # 🔹 Mover estos pasos después de ejecutar Cypress
      - name: Merge mochawesome reports
        if: always()
        run: npm run merge-reports || true

      - name: Generate HTML report
        if: always()
        run: npm run generate-report || true

      - name: Upload Cypress Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/index.html

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./cypress/reports
          destination_dir: ${{ env.ENVIRONMENT }}/${{ env.TEST_SUITE }}
          publish_branch: gh-pages
          external_repository: andreadev14/cypress_reports
